import {
  DEFAULT_SLOTS,
  type Driver,
  type Family,
  type Ride,
  type Anchor,
} from './types';
export const anchors: Anchor[] = [
  {
    id: 'marcus',
    name: 'Marcus High School',
    address: '5707 Morriss Road, Flower Mound, TX',
    lat: 33.0609,
    lng: -97.0583,
    category: 'School',
    notes: 'Meet at the front visitor parking area.',
    active: true,
  },
  {
    id: 'cac',
    name: 'Community Activity Center',
    address: '1200 Gerault Road, Flower Mound, TX',
    lat: 33.0078,
    lng: -97.0513,
    category: 'Recreation',
    notes: 'Meet at the main entrance. Confirm pickup with the coordinator.',
    active: true,
  },
  {
    id: 'library',
    name: 'Flower Mound Library',
    address: '3030 Broadmoor Lane, Flower Mound, TX',
    lat: 33.0291,
    lng: -97.073,
    category: 'Learning',
    notes: 'Main entrance pickup zone.',
    active: true,
  },
  {
    id: 'heritage',
    name: 'Heritage Park',
    address: '600 Spinks Road, Flower Mound, TX',
    lat: 33.0193,
    lng: -97.0403,
    category: 'Sports',
    notes: 'Use the designated parking area.',
    active: true,
  },
];
export function sampleData() {
  const now = Date.now(),
    stamp = new Date(now).toISOString();
  const names = [
    'Aiden Mitchell',
    'Sophia Chen',
    'James Carter',
    'Mia Patel',
    'Lucas Reed',
    'Isabella Garcia',
    'Olivia Bennett',
    'Ethan Brooks',
  ];
  const drivers: Driver[] = names.map((name, i) => ({
    id: 'd' + (i + 1),
    name,
    email: name.toLowerCase().replace(' ', '.') + '@example.com',
    phone: '+1214555010' + i,
    school: 'Marcus High School',
    dob: '2008-01-15',
    vehicle: [
      'White Honda Civic',
      'Silver Toyota Corolla',
      'Blue Hyundai Elantra',
    ][i % 3],
    plate: 'DEMO ' + (101 + i),
    licenseExpiry: '2028-06-30',
    insuranceExpiry: '2027-06-30',
    status: i < 6 ? 'approved' : 'review',
    licenseChecked: i < 6,
    insuranceChecked: i < 6,
    guardianConsent: i < 6,
    screeningChecked: i < 6,
    notes: 'Fictional practice profile. No real identity or documents.',
    availability: DEFAULT_SLOTS.map((s) => ({
      ...s,
      start: '00:00',
      end: '23:59',
      enabled: true,
    })),
    createdAt: stamp,
    hours: 0,
    rides: 0,
    rating: 0,
  }));
  const familyNames = [
    ['Sarah Wilson', 'Emma Wilson'],
    ['Michael Davis', 'Noah Davis'],
    ['Rachel Kim', 'Lily Kim'],
    ['David Thompson', 'Ethan Thompson'],
    ['Jennifer Lopez', 'Ava Lopez'],
    ['Priya Shah', 'Arjun Shah'],
  ];
  const families: Family[] = familyNames.map(([guardian, student], i) => ({
    id: 'f' + (i + 1),
    guardian,
    student,
    email: guardian.toLowerCase().replace(' ', '.') + '@example.com',
    phone: '+1214555020' + i,
    school: 'Marcus High School',
    consent: true,
    emergency: '+1214555030' + i,
    notes: 'Fictional practice household.',
    createdAt: stamp,
  }));
  const rides: Ride[] = [];
  const statusList = [
    'in_progress',
    'accepted',
    'pending',
    'pending',
    'accepted',
  ] as const;
  for (let i = 0; i < 5; i++)
    rides.push({
      id: 'KY-' + (1042 + i),
      familyId: 'f' + (i + 1),
      driverId: i === 2 || i === 3 ? null : 'd' + (i === 0 ? 1 : i + 1),
      pickupId: 'marcus',
      dropoffId: ['cac', 'library', 'heritage'][i % 3],
      scheduledAt: new Date(now + (i - 1) * 3600000).toISOString(),
      status: statusList[i],
      activity: [
        'Basketball practice',
        'Homework club',
        'Soccer training',
        'Music lesson',
        'Volunteering',
      ][i],
      notes: '',
      createdAt: stamp,
      updatedAt: stamp,
      startedAt: i === 0 ? new Date(now - 300000).toISOString() : null,
      acceptedAt: i === 0 ? new Date(now - 1200000).toISOString() : null,
      arrivedAt: i === 0 ? new Date(now - 600000).toISOString() : null,
      completedAt: null,
      otp: null,
      otpExpiresAt: null,
      otpAttempts: 0,
      lat: i === 0 ? 33.0429 : null,
      lng: i === 0 ? -97.0554 : null,
      accuracy: i === 0 ? 10 : null,
      locationAt: i === 0 ? stamp : null,
      locationSource: i === 0 ? 'simulation' : null,
      rating: null,
      feedback: '',
      cancelReason: '',
    });
  for (let i = 0; i < 18; i++) {
    const start = new Date(now - (i + 2) * 3600000).toISOString();
    rides.push({
      id: 'KY-' + (1001 + i),
      familyId: 'f' + ((i % 6) + 1),
      driverId: 'd' + ((i % 6) + 1),
      pickupId: 'marcus',
      dropoffId: ['cac', 'library', 'heritage'][i % 3],
      scheduledAt: start,
      status: 'completed',
      activity: ['Basketball practice', 'Tutoring', 'Soccer training'][i % 3],
      notes: '',
      createdAt: start,
      updatedAt: start,
      startedAt: start,
      acceptedAt: new Date(Date.parse(start) - 15 * 60000).toISOString(),
      arrivedAt: new Date(Date.parse(start) - 5 * 60000).toISOString(),
      completedAt: new Date(new Date(start).getTime() + 1200000).toISOString(),
      otp: null,
      otpExpiresAt: null,
      otpAttempts: 0,
      lat: null,
      lng: null,
      locationAt: null,
      accuracy: null,
      rating: 5,
      feedback: 'Thank you for the ride!',
      cancelReason: '',
    });
  }
  return { drivers, families, rides, anchors };
}
